version: '2'
services:

    mongodb:
      image: mongo:4.4.6
      volumes:
        - ./.data/db:/data/db
      ports:
        - 27017:27017

    elasticsearch:
      image: elasticsearch:2.4.0
      volumes:
        - ./.data/elastic:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
        - 9300:9300

#    geotrekapidae:
#      image: geo:latest
#      volumes:
#        - ./.data/geo:/home
#      ports:
#        - 3003:3003

#networks:
#    myapp:
#        driver: bridge
