version: '2.1'
services:
    mongodb:
      image: mongo:4.4.6
      command: mongod --auth
      volumes:
        - ./.data/db:/data/db
#        - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      ports:
        - 27017:27017
#      environment:
#        - MONGO_INITDB_DATABASE=admin
#        - MONGO_INITDB_ROOT_USERNAME=mongodb
#        - MONGO_INITDB_ROOT_PASSWORD=mongodb
      container_name: mongodb
      user: 1004:1004
volumes:
  mongodbdata:
    driver: local

